// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "UniversalBluetooth.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace universal_bluetooth_classic {
using flutter::BasicMessageChannel;
using flutter::CustomEncodableValue;
using flutter::EncodableList;
using flutter::EncodableMap;
using flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
  return FlutterError(
      "channel-error",
      "Unable to establish connection on channel: '" + channel_name + "'.",
      EncodableValue(""));
}

// BluetoothDevice

BluetoothDevice::BluetoothDevice(
  const std::string& address,
  bool paired,
  int64_t rssi)
 : address_(address),
    paired_(paired),
    rssi_(rssi) {}

BluetoothDevice::BluetoothDevice(
  const std::string& address,
  const std::string* name,
  bool paired,
  const bool* is_connected_with_hid,
  int64_t rssi,
  const DeviceClass* device_class,
  const DeviceType* device_type)
 : address_(address),
    name_(name ? std::optional<std::string>(*name) : std::nullopt),
    paired_(paired),
    is_connected_with_hid_(is_connected_with_hid ? std::optional<bool>(*is_connected_with_hid) : std::nullopt),
    rssi_(rssi),
    device_class_(device_class ? std::optional<DeviceClass>(*device_class) : std::nullopt),
    device_type_(device_type ? std::optional<DeviceType>(*device_type) : std::nullopt) {}

const std::string& BluetoothDevice::address() const {
  return address_;
}

void BluetoothDevice::set_address(std::string_view value_arg) {
  address_ = value_arg;
}


const std::string* BluetoothDevice::name() const {
  return name_ ? &(*name_) : nullptr;
}

void BluetoothDevice::set_name(const std::string_view* value_arg) {
  name_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void BluetoothDevice::set_name(std::string_view value_arg) {
  name_ = value_arg;
}


bool BluetoothDevice::paired() const {
  return paired_;
}

void BluetoothDevice::set_paired(bool value_arg) {
  paired_ = value_arg;
}


const bool* BluetoothDevice::is_connected_with_hid() const {
  return is_connected_with_hid_ ? &(*is_connected_with_hid_) : nullptr;
}

void BluetoothDevice::set_is_connected_with_hid(const bool* value_arg) {
  is_connected_with_hid_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void BluetoothDevice::set_is_connected_with_hid(bool value_arg) {
  is_connected_with_hid_ = value_arg;
}


int64_t BluetoothDevice::rssi() const {
  return rssi_;
}

void BluetoothDevice::set_rssi(int64_t value_arg) {
  rssi_ = value_arg;
}


const DeviceClass* BluetoothDevice::device_class() const {
  return device_class_ ? &(*device_class_) : nullptr;
}

void BluetoothDevice::set_device_class(const DeviceClass* value_arg) {
  device_class_ = value_arg ? std::optional<DeviceClass>(*value_arg) : std::nullopt;
}

void BluetoothDevice::set_device_class(const DeviceClass& value_arg) {
  device_class_ = value_arg;
}


const DeviceType* BluetoothDevice::device_type() const {
  return device_type_ ? &(*device_type_) : nullptr;
}

void BluetoothDevice::set_device_type(const DeviceType* value_arg) {
  device_type_ = value_arg ? std::optional<DeviceType>(*value_arg) : std::nullopt;
}

void BluetoothDevice::set_device_type(const DeviceType& value_arg) {
  device_type_ = value_arg;
}


EncodableList BluetoothDevice::ToEncodableList() const {
  EncodableList list;
  list.reserve(7);
  list.push_back(EncodableValue(address_));
  list.push_back(name_ ? EncodableValue(*name_) : EncodableValue());
  list.push_back(EncodableValue(paired_));
  list.push_back(is_connected_with_hid_ ? EncodableValue(*is_connected_with_hid_) : EncodableValue());
  list.push_back(EncodableValue(rssi_));
  list.push_back(device_class_ ? CustomEncodableValue(*device_class_) : EncodableValue());
  list.push_back(device_type_ ? CustomEncodableValue(*device_type_) : EncodableValue());
  return list;
}

BluetoothDevice BluetoothDevice::FromEncodableList(const EncodableList& list) {
  BluetoothDevice decoded(
    std::get<std::string>(list[0]),
    std::get<bool>(list[2]),
    std::get<int64_t>(list[4]));
  auto& encodable_name = list[1];
  if (!encodable_name.IsNull()) {
    decoded.set_name(std::get<std::string>(encodable_name));
  }
  auto& encodable_is_connected_with_hid = list[3];
  if (!encodable_is_connected_with_hid.IsNull()) {
    decoded.set_is_connected_with_hid(std::get<bool>(encodable_is_connected_with_hid));
  }
  auto& encodable_device_class = list[5];
  if (!encodable_device_class.IsNull()) {
    decoded.set_device_class(std::any_cast<const DeviceClass&>(std::get<CustomEncodableValue>(encodable_device_class)));
  }
  auto& encodable_device_type = list[6];
  if (!encodable_device_type.IsNull()) {
    decoded.set_device_type(std::any_cast<const DeviceType&>(std::get<CustomEncodableValue>(encodable_device_type)));
  }
  return decoded;
}


PigeonInternalCodecSerializer::PigeonInternalCodecSerializer() {}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
  uint8_t type,
  flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<DeviceClass>(enum_arg_value));
      }
    case 130: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<DeviceType>(enum_arg_value));
      }
    case 131: {
        return CustomEncodableValue(BluetoothDevice::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    default:
      return flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
  const EncodableValue& value,
  flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(DeviceClass)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<DeviceClass>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(DeviceType)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<DeviceType>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(BluetoothDevice)) {
      stream->WriteByte(131);
      WriteValue(EncodableValue(std::any_cast<BluetoothDevice>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by FlutterAccessoryPlatformChannel.
const flutter::StandardMessageCodec& FlutterAccessoryPlatformChannel::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `FlutterAccessoryPlatformChannel` to handle messages through the `binary_messenger`.
void FlutterAccessoryPlatformChannel::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  FlutterAccessoryPlatformChannel* api) {
  FlutterAccessoryPlatformChannel::SetUp(binary_messenger, api, "");
}

void FlutterAccessoryPlatformChannel::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  FlutterAccessoryPlatformChannel* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.universal_bluetooth_classic.FlutterAccessoryPlatformChannel.showBluetoothAccessoryPicker" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_with_names_arg = args.at(0);
          if (encodable_with_names_arg.IsNull()) {
            reply(WrapError("with_names_arg unexpectedly null."));
            return;
          }
          const auto& with_names_arg = std::get<EncodableList>(encodable_with_names_arg);
          api->ShowBluetoothAccessoryPicker(with_names_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.universal_bluetooth_classic.FlutterAccessoryPlatformChannel.startScan" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->StartScan();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.universal_bluetooth_classic.FlutterAccessoryPlatformChannel.stopScan" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->StopScan();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.universal_bluetooth_classic.FlutterAccessoryPlatformChannel.isScanning" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<bool> output = api->IsScanning();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.universal_bluetooth_classic.FlutterAccessoryPlatformChannel.getPairedDevices" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<EncodableList> output = api->GetPairedDevices();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.universal_bluetooth_classic.FlutterAccessoryPlatformChannel.pair" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_address_arg = args.at(0);
          if (encodable_address_arg.IsNull()) {
            reply(WrapError("address_arg unexpectedly null."));
            return;
          }
          const auto& address_arg = std::get<std::string>(encodable_address_arg);
          api->Pair(address_arg, [reply](ErrorOr<bool>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.universal_bluetooth_classic.FlutterAccessoryPlatformChannel.unpair" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_address_arg = args.at(0);
          if (encodable_address_arg.IsNull()) {
            reply(WrapError("address_arg unexpectedly null."));
            return;
          }
          const auto& address_arg = std::get<std::string>(encodable_address_arg);
          api->Unpair(address_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue FlutterAccessoryPlatformChannel::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue FlutterAccessoryPlatformChannel::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

// Generated class from Pigeon that represents Flutter messages that can be called from C++.
FlutterAccessoryCallbackChannel::FlutterAccessoryCallbackChannel(flutter::BinaryMessenger* binary_messenger)
 : binary_messenger_(binary_messenger),
    message_channel_suffix_("") {}

FlutterAccessoryCallbackChannel::FlutterAccessoryCallbackChannel(
  flutter::BinaryMessenger* binary_messenger,
  const std::string& message_channel_suffix)
 : binary_messenger_(binary_messenger),
    message_channel_suffix_(message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "") {}

const flutter::StandardMessageCodec& FlutterAccessoryCallbackChannel::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

void FlutterAccessoryCallbackChannel::OnDeviceDiscover(
  const BluetoothDevice& device_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.universal_bluetooth_classic.FlutterAccessoryCallbackChannel.onDeviceDiscover" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    CustomEncodableValue(device_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

void FlutterAccessoryCallbackChannel::OnDeviceRemoved(
  const BluetoothDevice& device_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.universal_bluetooth_classic.FlutterAccessoryCallbackChannel.onDeviceRemoved" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    CustomEncodableValue(device_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

}  // namespace universal_bluetooth_classic
