name: universal_bluetooth_example
description: "Demonstrates how to use the universal_bluetooth_classic plugin."
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  device_info_plus: ^9.0.2
  universal_bluetooth_classic:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4
  package_rename: ^1.10.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "../assets/universal_bluetooth_classic_maestro_icon.png"
  remove_alpha_ios: true
  windows:
    generate: true
    image_path: "../assets/universal_bluetooth_classic_maestro_icon.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "../assets/universal_bluetooth_classic_maestro_icon.png"
