name: universal_bluetooth
description: Bluetooth Classic & External Accessory for Flutter
version: 0.2.0
homepage: https://navideck.com
repository: https://github.com/Navideck/universal_bluetooth
issue_tracker: https://github.com/Navideck/universal_bluetooth/issues
documentation: https://github.com/Navideck/universal_bluetooth#readme

funding:
  - https://github.com/sponsors/Navideck

topics:
  - bluetooth
  - bluetooth-hid
  - external-accessory
  - ios-external-accessory
  - bluetooth-accessories

platforms:
  android:
  ios:
  macos:
  windows:
  linux:

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  bluez: ^0.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  pigeon: ^22.4.0

flutter:
  plugin:
    platforms:
      android:
        package: com.navideck.universal_bluetooth
        pluginClass: UniversalBluetoothPlugin
      ios:
        pluginClass: UniversalBluetoothPlugin
      macos:
        pluginClass: UniversalBluetoothPlugin
      windows:
        pluginClass: UniversalBluetoothPluginCApi
