// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct EAAccessory {
  var isConnected: Bool
  var connectionID: Int64
  var manufacturer: String
  var name: String
  var modelNumber: String
  var serialNumber: String
  var firmwareRevision: String
  var hardwareRevision: String
  var dockType: String
  var protocolStrings: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> EAAccessory? {
    let isConnected = pigeonVar_list[0] as! Bool
    let connectionID = pigeonVar_list[1] as! Int64
    let manufacturer = pigeonVar_list[2] as! String
    let name = pigeonVar_list[3] as! String
    let modelNumber = pigeonVar_list[4] as! String
    let serialNumber = pigeonVar_list[5] as! String
    let firmwareRevision = pigeonVar_list[6] as! String
    let hardwareRevision = pigeonVar_list[7] as! String
    let dockType = pigeonVar_list[8] as! String
    let protocolStrings = pigeonVar_list[9] as! [String]

    return EAAccessory(
      isConnected: isConnected,
      connectionID: connectionID,
      manufacturer: manufacturer,
      name: name,
      modelNumber: modelNumber,
      serialNumber: serialNumber,
      firmwareRevision: firmwareRevision,
      hardwareRevision: hardwareRevision,
      dockType: dockType,
      protocolStrings: protocolStrings
    )
  }
  func toList() -> [Any?] {
    return [
      isConnected,
      connectionID,
      manufacturer,
      name,
      modelNumber,
      serialNumber,
      firmwareRevision,
      hardwareRevision,
      dockType,
      protocolStrings,
    ]
  }
}

private class ExternalAccessoryPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return EAAccessory.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class ExternalAccessoryPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? EAAccessory {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class ExternalAccessoryPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ExternalAccessoryPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ExternalAccessoryPigeonCodecWriter(data: data)
  }
}

class ExternalAccessoryPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ExternalAccessoryPigeonCodec(readerWriter: ExternalAccessoryPigeonCodecReaderWriter())
}


/// Flutter -> Native
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ExternalAccessoryChannel {
  func showBluetoothAccessoryPicker(withNames: [String], completion: @escaping (Result<Void, Error>) -> Void)
  func closeEASession(protocolString: String?, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ExternalAccessoryChannelSetup {
  static var codec: FlutterStandardMessageCodec { ExternalAccessoryPigeonCodec.shared }
  /// Sets up an instance of `ExternalAccessoryChannel` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ExternalAccessoryChannel?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let showBluetoothAccessoryPickerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.universal_bluetooth.ExternalAccessoryChannel.showBluetoothAccessoryPicker\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showBluetoothAccessoryPickerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let withNamesArg = args[0] as! [String]
        api.showBluetoothAccessoryPicker(withNames: withNamesArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      showBluetoothAccessoryPickerChannel.setMessageHandler(nil)
    }
    let closeEASessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.universal_bluetooth.ExternalAccessoryChannel.closeEASession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeEASessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let protocolStringArg: String? = nilOrValue(args[0])
        api.closeEASession(protocolString: protocolStringArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      closeEASessionChannel.setMessageHandler(nil)
    }
  }
}
/// Native -> Flutter
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol ExternalAccessoryCallbackChannelProtocol {
  func accessoryConnected(accessory accessoryArg: EAAccessory, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func accessoryDisconnected(accessory accessoryArg: EAAccessory, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class ExternalAccessoryCallbackChannel: ExternalAccessoryCallbackChannelProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: ExternalAccessoryPigeonCodec {
    return ExternalAccessoryPigeonCodec.shared
  }
  func accessoryConnected(accessory accessoryArg: EAAccessory, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.universal_bluetooth.ExternalAccessoryCallbackChannel.accessoryConnected\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([accessoryArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func accessoryDisconnected(accessory accessoryArg: EAAccessory, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.universal_bluetooth.ExternalAccessoryCallbackChannel.accessoryDisconnected\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([accessoryArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
